feat(bin): overhaul notify-all command to use ntfy

diff --git a/bin/.local/bin/notify-all b/bin/.local/bin/notify-all
--- a/bin/.local/bin/notify-all
+++ b/bin/.local/bin/notify-all
@@ -2,9 +2,9 @@
 # ==============================================================================
 # Script Name: notify-all
 # Description: sends a notification to all listed devices
-# Usage: notify-all <message>
+# Usage: notify-all [options] <message>
 # Author: Danny Harris
-# Dependencies: notify-send, paplay, kdeconnect-cli
+# Dependencies: notify-send, paplay
 # ==============================================================================
 
 # -e: exit on error, -u: treat unset variables as errors, -o pipefail: pipe will fail if any command fails
@@ -12,50 +12,73 @@ set -euo pipefail
 
 # global variables
 message="$*"
-urgency="normal"
+summary=''
+urgency=1
+title='notify-all'
+# TODO: experiment with action buttons
 
-# TODO: replace all 'echo' with 'printf'
 usage() {
-    echo "Usage:"
-    echo -e "        notify-all \e[1m<message>\e[0m"
+    local cmd="${0##*/}"
+    cat <<-EOF
+		Notify all connected devices
+
+		Usage: $cmd [options] <message>
+
+		Options:
+		  -t TITLE          title of notification
+		  -s SUMMARY        summary of message
+		  -u [0-3]          change urgency of notification 
+		  -h                show this help message
+
+		Useful Icons:
+		   ⏳🍬📦🏛🔔📜🧿😈🍬🔷💀🫆🪳🍖🧊🌐🧭🛑⚓🌜🕹🎲🃏💻💾📚💼📅📋🔒🛠🛡⚠⚡
+
+		Examples:
+		  $cmd -t 'Urgent Message:' -u 2 there was an error
+		  $cmd -t 'REMINDER' -i package -s 'this is a summary' do this thing
+	EOF
 }
+
 error() {
-    echo "error: $*" >&2
-    usage >&2
+    printf 'error: %s\n' "$*" >&2
     exit 1
 }
 
-# check for empty message
-if [ -z "$message" ]; then
+# handle arguments
+while getopts s:u:t:h flag; do
+    case "${flag}" in
+    u) urgency="$OPTARG" ;;
+    t) title="$OPTARG" ;;
+    s) summary="$OPTARG" ;;
+    h)
+        usage
+        exit 0
+        ;;
+    ?)
+        exit 2
+        ;;
+    esac
+done
+shift $((OPTIND - 1))
+message="$*"
+if [[ -z "$message" ]]; then
     error "no message provided"
 fi
 
-# check last argument for -h or --help
-if [ "${*: -1}" == "-h" ] || [ "${*: -1}" == "--help" ]; then
-    usage
-    exit 0
-fi
+case "$urgency" in
+0) urgency_notify_send="low" urgency_ntfy="low" ;;
+1) urgency_notify_send="normal" urgency_ntfy="default" ;;
+2) urgency_notify_send="critical" urgency_ntfy="high" ;;
+3) urgency_notify_send="critical" urgency_ntfy="max" ;;
+*) error "invalid argument for -i: $urgency" ;;
+esac
 
-if [[ "$1" == "important" || "$1" == "-i" ]]; then
-    urgency="critical"
-    shift
-    message="$*"
-fi
-
-# notify all kdeconnect devices
-notify-kdeconnect-devices() {
-    local kde_devices
-    mapfile -t kde_devices < <(kdeconnect-cli --list-available --name-only)
-    # check for available devices
-    if [ -z "${kde_devices[*]}" ]; then
-        error "no kdeconnect devices found"
-    else
-        for device in "${kde_devices[@]}"; do
-            echo "notifying $device"
-            kdeconnect-cli --ping-msg "$message" -n "$device"
-        done
-    fi
-
+# notify all devices
+notify-devices() {
+    printf 'notifying devices\n'
+    local summary_modified=''
+    [[ -n "$summary" ]] && summary_modified="[$summary]"
+    curl -sd "$summary_modified$message" -H "Title: $title" -H "Priority: $urgency_ntfy" -H "Markdown: yes" olympus:8234/alerts >/dev/null || error "failed to notify devices"
 }
 
 # play desktop notification sound
@@ -63,9 +86,9 @@ play-desktop-sound() {
     # check for paplay
     if command -v paplay &>/dev/null; then
         # check for oga file
-        local AUDIO_FILE="/usr/share/sounds/freedesktop/stereo/complete.oga"
-        if [ -f "$AUDIO_FILE" ]; then
-            paplay "$AUDIO_FILE"
+        local audio_file="/usr/share/sounds/freedesktop/stereo/complete.oga"
+        if [ -f "$audio_file" ]; then
+            paplay "$audio_file"
         else
             error "no oga file found for paplay"
         fi
@@ -76,23 +99,20 @@ play-desktop-sound() {
 
 # notify desktop
 notify-desktop() {
-    echo 'notifying desktop'
-    notify-send --app-name="notify-all" --icon="clock" -t 5000 --urgency="$urgency" "$message"
+    printf 'notifying desktop\n'
+    notify-send --app-name="$title" --icon="clock" -t 5000 --urgency="$urgency_notify_send" "$summary" "$message"
 }
 
 # check if notify-send is installed and notify desktop
 if command -v notify-send &>/dev/null; then
     notify-desktop
-    play-desktop-sound
+    ((urgency > 0)) && play-desktop-sound
+    ((urgency >= 3)) && play-desktop-sound
 else
     error "notify-send is not installed"
 fi
 
-# check if kdeconnect-cli is installed and notify all devices
-if command -v kdeconnect-cli &>/dev/null; then
-    notify-kdeconnect-devices
-else
-    error "kdeconnect-cli is not installed"
-fi
+# notify all devices
+notify-devices
 
 # vim: set ft=sh:
